version: '3.8'

services:

  mongo:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_USERNAME=test_user
      - MONGODB_PASSWORD=test_password
      - MONGODB_DATABASE=test

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/