version: '3.1'

services:
  db:
    image: mysql:8.0.36
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
#    volumes:
#      - ./data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql