import "@/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Project",
  description: "Generated by create next app for fullstack web development",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={"h-full " + inter.className}>{children}</body>
    </html>
  );
}
