import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import LocalProxy from "@/components/client/LocalProxy";
import { validateToken } from "@/middleware/AuthService";
import Navbar from "@/components/client/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Project",
  description: "Generated by create next app for fullstack web development",
};

async function getData() {
  return validateToken(cookies().get("token"));
}

export default async function PrivateLayout({ children }) {
  const data = await getData();

  if (!data) {
    return (
      <html lang="en">
        <body>
          <LocalProxy page="/" />
        </body>
      </html>
    );
  } else {
    return (
      <html lang="en" className="h-full bg-white">
        <body>
          <Navbar />
          <div className={"h-full " + inter.className}>{children}</div>
        </body>
      </html>
    );
  }
}
