import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hola!",
  description: "Generated by create next app for fullstack web development",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="es" className="h-full bg-white">
      <body className={"h-full " + inter.className}>{children}</body>
    </html>
  );
}
