### POST /user/register
POST {{base_url}}/user/register
Content-Type: application/json

{
  "email": "victor1@victor.com"
}

### POST /user/register
POST {{base_url}}/user/register
Content-Type: application/json

{
  "email": "victor@gmail.com",
  "password": "this_is_a_password"
}