### POST /user/register
POST {{base_url}}/user/register
Content-Type: application/json

{
  "email": "victor5@victor.com",
  "password": "this_is_a_password"
}

### POST /auth/login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "victor1@victor.com",
  "password": "this_is_a_password"
}

### POST /user/register
POST {{base_url}}/user/register
Content-Type: application/json

{
  "email": "victor@gmail.com",
  "password": "this_is_a_password"
}
