### POST /user/register
POST {{base_url}}/user/register
Content-Type: application/json

{
  "email": "victor0@victor.com",
  "password": "this_is_a_password"
}

### POST /auth/login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "victor0@victor.com",
  "password": "this_is_a_password"
}

### GET /user-toy/list
GET {{base_url}}/user-toy/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjYwZWFkMjVhNzViYzllNGE5NzhhNDc2IiwiaWF0IjoxNzEyMjM3ODY3LCJleHAiOjE3MTIyNDE0Njd9.SKbmWUBBMYkSjmhrDds1EF7Nw6Md5HEa9eTaQoYwzIU

### GET /user-toy/list
GET {{base_url}}/user-toy/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjYwZTA0NTg2MDM0YTliMWZiMjllNzc3IiwiaWF0IjoxNzEyMTk0NjU0LCJleHAiOjE3MTIxOTgyNTR9.lt2gjvBqqHmoYOSvroF1I2-ayljcVxMvQ7Ambuoj41I

### POST /user-toy/create
POST {{base_url}}/user-toy/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjYwZWFkMjVhNzViYzllNGE5NzhhNDc2IiwiaWF0IjoxNzEyMjM3ODY3LCJleHAiOjE3MTIyNDE0Njd9.SKbmWUBBMYkSjmhrDds1EF7Nw6Md5HEa9eTaQoYwzIU

{
  "toy": "gato",
  "color": "verde",
  "accessory": "notebook"
}

### GET /toy/list
GET {{base_url}}/toy/list
Content-Type: application/json

### GET /color/list
GET {{base_url}}/color/list
Content-Type: application/json

### GET /accessory/list
GET {{base_url}}/accessory/list
Content-Type: application/json
