name: Jest

on: [ push ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-coverage

      - name: Use Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: coverage
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

      - name: Publish to Testspace
        uses: testspace-com/setup-testspace@v1
        with:
          domain: vdacun1.testspace.com
          token: ${{ secrets.TESTSPACE_TOKEN }}
        run: testspace ./coverage/clover.xml
