name: Jest

on: [ push ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-coverage
      - run: npm run test-reporters

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

      - name: Testspace
        uses: testspace-com/setup-testspace@v1
        with:
          token: ${{ secrets.TESTSPACE_TOKEN }}
          domain: vdacun1.testspace.com
      - run: testspace ./junit.xml ./coverage/clover.xml