name: CI

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install Python 2.7
        run: sudo apt-get install python2.7
      - name: Clone lcov-to-cobertura-xml
        run: git clone https://github.com/eriwen/lcov-to-cobertura-xml.git
      - run: npm ci
      - run: npm run test-coverage
      - name: Install lcov-result-merger
        run: npm install lcov-result-merger
      - name: Merge LCOV files
        run: ./node_modules/.bin/lcov-result-merger 'coverage/**/lcov.info' > lcov.info
      - name: Convert LCOV to Cobertura XML
        run: python lcov-to-cobertura-xml/lcov_cobertura/lcov_cobertura.py lcov.info --output coverage.xml
      - name: Use Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage.xml