name: Test Coverage

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run test-coverage
      - name: Install lcov-result-merger
        run: npm install lcov-result-merger
      - name: Merge LCOV files
        run: ./node_modules/.bin/lcov-result-merger 'coverage/**/lcov.info' > lcov.info
      - name: Publish Coverage Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'lcov.info'
        if: always()