name: Code Quality Check

on:
  pull_request:
    paths:
    - 'frontend-project/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: cd frontend-project && npm ci

    - name: Run ESLint
      run: cd frontend-project && npx eslint .