name: Testspace

on: [ push ]

jobs:

  Testspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-reporters

      - name: Use Testspace
        uses: testspace-com/setup-testspace@v1
        with:
          token: ${{ secrets.TESTSPACE_TOKEN }}
          domain: vdacun1.testspace.com
      - run: testspace ./junit.xml